include_directories(.)

# add deps and initcode
add_subdirectory(deps)
add_subdirectory(init)
# set output dir
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/bin/app)

# add initcode
if(RISCV)
    file(GLOB USER_PROGS app/*.c tests/*.c)
    message(STATUS "Matched source files: ${USER_PROGS}")
    set(USER_TARGETS "")
    set(userApps "")
    foreach(USER_PROG ${USER_PROGS})
        get_filename_component(USER_PROG_NAME ${USER_PROG} NAME_WE)
        LIST(APPEND USER_TARGETS bin/app/${USER_PROG_NAME})
        list(APPEND userApps ${USER_PROG_NAME})
        add_executable(${USER_PROG_NAME} ${USER_PROG})
        set_target_properties(${USER_PROG_NAME} PROPERTIES LINK_FLAGS "-T ${CMAKE_CURRENT_SOURCE_DIR}/user.ld -z max-page-size=4096")
        target_link_libraries(${USER_PROG_NAME} ulib)
    endforeach(USER_PROG)
elseif(LOONGARCH)
    file(GLOB USER_PROGS app/*.c tests/*.c)
    message(STATUS "Matched source files: ${USER_PROGS}")
    set(USER_TARGETS "")
    set(userApps "")
    foreach(USER_PROG ${USER_PROGS})
        get_filename_component(USER_PROG_NAME ${USER_PROG} NAME_WE)
        LIST(APPEND USER_TARGETS bin/app/${USER_PROG_NAME})
        list(APPEND userApps ${USER_PROG_NAME})
        add_executable(${USER_PROG_NAME} ${USER_PROG})
        set_target_properties(${USER_PROG_NAME} PROPERTIES LINK_FLAGS "-T ${CMAKE_CURRENT_SOURCE_DIR}/user-loongarch.ld -z max-page-size=4096")
        target_link_libraries(${USER_PROG_NAME} ulib)
    endforeach(USER_PROG)
endif()

set(USER_TARGETS ${USER_TARGETS} PARENT_SCOPE)
set(userApps ${userApps} PARENT_SCOPE)
